{% set version = "0.3" %}

package:
  name: pymesh2
  version: {{ version }}

source:
  url: https://github.com/PyMesh/PyMesh/releases/download/v{{ version }}/pymesh2-{{ version }}-cp36-cp36m-linux_x86_64.whl
  sha256: e1e1d6073144d2c8fba9d6df12f56ef92a65245db25e24c28b6abefa9bc65154

build:
  number: 1
  skip: true  # [not (linux and py36)]
  script: {{ PYTHON }} -m pip install --no-deps -vv --ignore-installed ./pymesh2-{{ version }}-cp36-cp36m-linux_x86_64.whl

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - pymesh  # [not linux]

about:
  home: https://github.com/PyMesh/PyMesh
  license: MPL
  # https://github.com/PyMesh/PyMesh/issues/180
  # license_file: 
  summary: Mesh Processing for Python

extra:
  recipe-maintainers:
    - ocefpaf
    - meredithmclinn
