travis:
  secure:
    BINSTAR_TOKEN: MXOs/W5bV6sBLsddE4SZ6LFAEHNju8iKt3cGASqcxNBfGcKn9qLyJcWauAeVDysd2gDJOJw6CYrmPdDNp5+HkwBFAMHs4bCVutVXvlP6yeXCLEZOTVE8x393SzGIAm0Jsr3Bjaec/Ek5bC8DCZ9GbpTwHq2fmg0xfYzS2j7CbMn469RlXEVCJ/8nUO9aKGGjEIp6uBHcu5EnTik8RyvK/8wJGCytPVGYO90Ok1NW3NIdEkCSR+3Wh5yR5PhNQpaYlW0eY3Zu6X0fBdbQcCqS7bx9bEGyGF9H761nClst3eo4ptHeyE/Ls9uXvMwISFL7uceGHr7/sPyRnhcBDyuBPZPAtMFZ4IiFyRURntl8/xTtAIMnZwapuHqb/LiLZcw7HlWGQL5/1dF79xG+oZpivPlAzli0/FzWv5hluyHZ5fL37Ffk5ZUUZLRV7F+4l3PsMe9AA0znGeTSwnITtACwHNvsRACBFWvvuKHj4CKxSrYyBKmv20HuMGUCfvqhua3BzUNDgg01Y9okjfnLDMBmOAPLIZsewWFXnex7HynI3zxzfSamQjY+Ezn+Fuc7xYePdPNGWZHkb+o10i3hZ1sVyZ3bfgjjWYWiCz62b+MgiwDc3C7dsYwM9d+PQxsSHUoXn68XQVjy352670Xdr9yl/WabwCI/x1ehbVWFoLg5mSk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
